import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import lfilter

# Config
TAPS = 100
SCALE_IN = 1 << 14   # Inputs and Coeffs are Q2.14

# --- 1. File Reading Functions ---

def read_hex(fname):
    """Reads Q2.14 Hex files (Inputs and Coefficients)"""
    vals = []
    try:
        with open(fname, "r") as f:
            for line in f:
                line = line.strip()
                if not line: continue
                v = int(line, 16)
                if v >= 0x8000: v -= 0x10000 # 16-bit signed
                vals.append(v)
    except FileNotFoundError:
        return np.array([])
    return np.array(vals)

def read_float(fname):
    """Reads standard float files (Verilog outputs are already floats)"""
    vals = []
    try:
        with open(fname, "r") as f:
            for line in f:
                line = line.strip()
                if not line: continue
                vals.append(float(line)) # Read directly as a float
    except FileNotFoundError:
        return np.array([])
    return np.array(vals)

# --- 2. Load & Reconstruct Coefficients ---

c_raw = read_hex("fir_coeff_q214.txt") / SCALE_IN
if len(c_raw) > 0:
    # Mirror the half-coefficients for the Optimized logic
    c_full = np.concatenate([c_raw[:50], c_raw[:50][::-1]]) 
else:
    c_full = np.zeros(TAPS)

# --- 3. Latencies (Match Verilog pipeline depths) ---
L_DIR = 3
L_GEN = 1
L_OPT = 53

freqs = [950, 1100, 2000]
plt.figure(figsize=(12, 10))

# --- 4. Plotting Loop ---
for i, f in enumerate(freqs):
    
    # Load Input Signal (Sine waves generated by Python)
    x_raw = read_hex(f"sine{f}_Q214.txt")
    if len(x_raw) == 0: continue
    x_float = x_raw / SCALE_IN
    
    # Python Golden Reference
    gold = lfilter(c_full, 1.0, x_float)
    
    # Load Verilog Outputs (Already scaled by testbench, so use read_float!)
    v_dir = read_float(f"out_direct_{f}.txt")
    v_gen = read_float(f"out_trans_{f}.txt")
    v_opt = read_float(f"out_opt_{f}.txt")

    # Align and Plot
    plt.subplot(3, 1, i+1)
    t_len = 150
    t = np.arange(t_len)
    
    plt.plot(t, gold[:t_len], 'k', alpha=0.3, lw=5, label="Golden (Python)")
    
    signals = [
        (v_dir[L_DIR:], "Direct", "-"),
        (v_gen[L_GEN:], "Transposed/Genvar", ":"),
        (v_opt[L_OPT:], "Optimized", "-.")
    ]

    for sig, lab, style in signals:
        if len(sig) >= t_len:
            plt.plot(t, sig[:t_len], style, label=f"{lab}")
        else:
            print(f"Warning: {lab} at {f}Hz only has {len(sig)} samples. Check simulation length.")

    plt.title(f"Frequency Response Comparison: {f} Hz")
    plt.ylabel("Amplitude")
    plt.grid(True, alpha=0.3)
    plt.legend(loc='upper right', fontsize='small')

plt.xlabel("Sample Index")
plt.tight_layout()
plt.show()